import { geistMono, geistSans, montserrat } from "@/components/Font";
import Navbar from "@/components/Navbar";
import "./global.scss";

export const metadata = {
  title: "Wadgaonkar Growth Academy",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.className} ${geistSans.className} ${geistMono.className}`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
